# Generated by Django 6.0.7 on 2026-08-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The URL: /products/<slug>. Changing it breaks existing links.', max_length=60, unique=True)),
                ('name', models.CharField(help_text='How the system is named everywhere it is referred to — cards, cross-links, the enquiry form. e.g. "Lift & Slide".', max_length=60)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Position in the carousel, the footer column and the cross-links. Lower shows first.')),
                ('is_published', models.BooleanField(default=True, help_text='Off removes the system from the site — every card, list and form option — without deleting it or its variants.')),
                ('page_title', models.CharField(blank=True, max_length=140)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('schema_name', models.CharField(blank=True, max_length=140)),
                ('schema_category', models.CharField(blank=True, max_length=140)),
                ('schema_description', models.CharField(blank=True, max_length=400)),
                ('hero_video', models.CharField(blank=True, max_length=300)),
                ('hero_video_file', models.FileField(blank=True, null=True, upload_to='catalogue/hero/')),
                ('hero_image', models.CharField(blank=True, max_length=300)),
                ('hero_image_file', models.ImageField(blank=True, null=True, upload_to='catalogue/hero/')),
                ('hero_title', models.CharField(blank=True, max_length=80)),
                ('hero_accent', models.CharField(blank=True, max_length=120)),
                ('hero_lede', models.CharField(blank=True, max_length=400)),
                ('overview_title_lead', models.CharField(blank=True, max_length=120)),
                ('overview_title_em', models.CharField(blank=True, max_length=120)),
                ('chips', models.JSONField(blank=True, default=list, help_text='["Panoramic", …]')),
                ('overview_body', models.JSONField(blank=True, default=list, help_text='["paragraph", …]')),
                ('stats', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list, help_text='[{title, copy}, …]')),
                ('series_note', models.CharField(blank=True, max_length=300)),
                ('fits', models.JSONField(blank=True, default=list, help_text='Series ids flagged "For <System>" on this page, e.g. ["105","135"].')),
                ('series_order', models.JSONField(blank=True, default=list, help_text="All twelve series ids in this page's grid order.")),
                ('card_video', models.CharField(blank=True, max_length=300)),
                ('card_video_file', models.FileField(blank=True, null=True, upload_to='catalogue/cards/')),
                ('card_poster', models.CharField(blank=True, max_length=300)),
                ('card_poster_file', models.ImageField(blank=True, null=True, upload_to='catalogue/cards/')),
                ('card_image', models.CharField(blank=True, max_length=300)),
                ('card_image_file', models.ImageField(blank=True, null=True, upload_to='catalogue/cards/')),
                ('teaser_lead', models.CharField(blank=True, max_length=80)),
                ('teaser_em', models.CharField(blank=True, max_length=80)),
                ('teaser_desc', models.TextField(blank=True)),
                ('teaser_specs', models.JSONField(blank=True, default=list, help_text='Three short strings.')),
                ('teaser_cta', models.CharField(blank=True, max_length=80)),
                ('enquiry_note', models.CharField(blank=True, help_text='One line shown under the system chips on the contact form when this system is chosen.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalogue_system',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable id within the system — also the clip filename. e.g. "two-track-door".', max_length=60)),
                ('name', models.CharField(help_text='As a specifier would name it.', max_length=90)),
                ('kind', models.CharField(blank=True, help_text='The eyebrow: "Window", "Door", "Door & Screen".', max_length=60)),
                ('lede', models.CharField(blank=True, help_text='ONE short sentence, ~55-65 characters. It sits over the clip, and every line of prose in front of the picture is a line of the product hidden.', max_length=200)),
                ('specs', models.JSONField(blank=True, default=list)),
                ('video', models.CharField(blank=True, max_length=300)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='catalogue/variants/')),
                ('poster', models.CharField(blank=True, max_length=300)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to='catalogue/variants/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogue.system')),
            ],
            options={
                'db_table': 'catalogue_variant',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('system', 'key'), name='catalogue_variant_unique_key')],
            },
        ),
    ]
