# Generated by Django 6.0.7 on 2026-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('avg_duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_daily_stat',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('date', 'path'), name='uniq_daily_stat_date_path')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='desktop', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_page_view',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_p_path_44ef74_idx'), models.Index(fields=['visitor_hash', 'created_at'], name='analytics_p_visitor_e541f2_idx')],
            },
        ),
    ]
