# Generated by Django 6.0.7 on 2026-08-10 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(help_text='Used in the filter bar and the deep link. Changing it breaks a shared /gallery?filter=<slug> link.', max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Position in the filter bar. Lower shows first.')),
                ('is_published', models.BooleanField(default=True, help_text='Off hides the tab. Its items stay on the site under "All".')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery categories',
                'db_table': 'gallery_category',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Photograph'), ('video', 'Film')], db_index=True, default='image', help_text='Photograph or film. A film needs a poster as well, or it shows as a black tile until it decodes.', max_length=10)),
                ('title', models.CharField(help_text='What this is — "Six-metre sliding elevation, Jubilee Hills". Shown on the tile and used as the image\'s alt text if the field below is left empty.', max_length=140)),
                ('caption', models.CharField(blank=True, help_text='Optional single line under the title in the lightbox. Not shown on the tile.', max_length=300)),
                ('alt_text', models.CharField(blank=True, help_text='What a person who cannot see the image needs to know. Leave it empty and the title is used — which is usually right, and is always better than nothing.', max_length=250)),
                ('image', models.CharField(blank=True, help_text='A path under client/public, or an absolute URL. Ignored if a file is uploaded below.', max_length=300)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video', models.CharField(blank=True, max_length=300)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('poster', models.CharField(blank=True, help_text='The still shown before a film plays.', max_length=300)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to='gallery/posters/')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items take a double-width tile in the grid. Use it sparingly — a grid where everything is featured is a grid.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Position in the grid. Lower shows first.')),
                ('is_published', models.BooleanField(default=True, help_text='Off removes it from the site without deleting it.')),
                ('shot_on', models.DateField(blank=True, help_text='Optional. Not shown on the page — it is here so the grid can be ordered newest-first when nobody has set an order.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Which filter tab this appears under. Optional — an item with no category still appears under "All".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='gallery.gallerycategory')),
                ('system', models.ForeignKey(blank=True, help_text="Optional. Which Glaze system is in the picture. It becomes a link from the gallery into that system's page, which is the whole reason to record it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='catalogue.system')),
            ],
            options={
                'db_table': 'gallery_item',
                'ordering': ('order', '-shot_on', '-created_at'),
                'indexes': [models.Index(fields=['is_published', 'order'], name='gallery_pub_order_idx')],
            },
        ),
    ]
