# Generated by Django 6.0.7 on 2026-07-31 19:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # pg_trgm powers the typo tolerance in chatbot/retrieval.py — without
        # it, TrigramSimilarity raises "function similarity(...) does not
        # exist" on the first question anyone asks. Declared here rather than
        # left as a manual psql step so a fresh deploy works from `migrate`
        # alone. Both are CREATE EXTENSION IF NOT EXISTS, so re-running is
        # harmless; they do require the migrating role to be superuser or to
        # have the extension pre-installed.
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_at', models.DateTimeField(auto_now=True)),
                ('entry_path', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'chatbot_session',
                'ordering': ('-last_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Visitor'), ('assistant', 'Assistant')], max_length=12)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('deflected', models.BooleanField(db_index=True, default=False)),
                ('answer_mode', models.CharField(blank=True, max_length=40)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chatbot_message',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('topic', models.CharField(choices=[('systems', 'Systems'), ('series', 'Series catalogue'), ('company', 'Company'), ('process', 'Process'), ('performance', 'Performance'), ('specification', 'Specification'), ('contact', 'Contact'), ('blog', 'Blog')], db_index=True, max_length=20)),
                ('source_label', models.CharField(max_length=120)),
                ('source_path', models.CharField(max_length=200)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_knowledge_chunk',
                'ordering': ('topic', 'title'),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_gin')],
            },
        ),
    ]
