"""
Django settings for glaze project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Every secret lives in server/glaze/.env, which is gitignored.
# Copy .env.example -> .env to get started.
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default on purpose — the app should refuse to boot rather than run on a
# predictable key that would let anyone forge JWTs.
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Required for SearchVectorField / GinIndex on the chatbot knowledge base.
    'django.contrib.postgres',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    'account',
    'siteconfig',
    'catalogue',
    'seo',
    'blog',
    'analytics',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'glaze.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'glaze.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL, via psycopg 3 — same backend string, see requirements.txt.
DB_ENGINE = env('DB_ENGINE', default='django.db.backends.postgresql')

if DB_ENGINE.endswith('sqlite3'):
    # Escape hatch, and it is NOT reachable by accident: it requires someone to
    # write DB_ENGINE=django.db.backends.sqlite3 into .env by hand. Postgres is
    # the default and still demands every credential explicitly — a *silent*
    # sqlite fallback in production would be far worse than a crash.
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': env('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }


# Cache
# ------------------------------------------------------------------
# ⚠ NOT left at the default, and this is a correctness fix rather than a
# performance one.
#
# Django's default cache is LocMemCache, which is PER PROCESS. Gunicorn runs
# several worker processes (3 by default here), and every DRF throttle counter
# — login, captcha, enquiry, track, comment, chat — is stored in the cache.
# With a per-process cache each worker keeps its own tally, so a client turned
# away by one worker simply lands on the next: THROTTLE_LOGIN=10/min actually
# admits 30/min, and THROTTLE_ENQUIRY=5/min admits 15. The limits silently
# mean N times whatever they say, where N is the worker count.
#
# The database backend is shared by every worker, so a limit means what it
# says. It costs one indexed query per throttled request — nothing beside the
# login or LLM call it is protecting. Redis is faster and is the right answer
# under real traffic; it is also an extra service to run, secure and back up,
# which a marketing site's rate limiter does not justify.
#
# ⚠ The table is NOT created by migrate. `manage.py createcachetable` makes it,
# and the container entrypoint runs that on every start (it is idempotent).
# Without the table every throttled request raises ProgrammingError, so if you
# run this project outside Docker, run that command once by hand.
CACHES = {
    'default': {
        'BACKEND': env(
            'CACHE_BACKEND',
            default='django.core.cache.backends.db.DatabaseCache',
        ),
        'LOCATION': env('CACHE_LOCATION', default='glaze_cache'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Argon2id first. It is the current password-hashing recommendation (PHC winner,
# OWASP's first choice) and is memory-hard, so a stolen hash resists GPU/ASIC
# cracking in a way PBKDF2-SHA256 does not. The rest of the list stays so that
# hashes written by an older deploy still verify — Django transparently upgrades
# each one to Argon2 on the owner's next successful login.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded media — blog featured images land here. Served by Django only while
# DEBUG is on (see glaze/urls.py); behind a real web server in production.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 5 MB. Blog hero images are recommended at 1200x630, which lands far under
# this even as PNG; the cap is here to stop an accidental multi-megabyte upload.
MAX_UPLOAD_SIZE_BYTES = env.int('MAX_UPLOAD_SIZE_BYTES', default=5 * 1024 * 1024)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication
# ------------------------------------------------------------------

AUTH_USER_MODEL = 'account.User'


def _env_bool(key, default):
    """env.bool() treats a blank value as False; here blank means 'not set'."""
    raw = env.str(key, default='').strip()
    return default if not raw else env.bool(key)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'account.authentication.CookieJWTAuthentication',
    ),
    # Default-deny. Every public endpoint (blog reads, the analytics beacon, the
    # captcha challenge) opts out explicitly with AllowAny, so a new view added
    # without a permission_classes line fails closed rather than leaking.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # Coarse per-IP ceilings. The real brute-force defence for login is the
        # per-account + per-IP lockout in account/security.py; this is the
        # cheap outer layer that keeps a flood off the database entirely.
        'login': env('THROTTLE_LOGIN', default='10/min'),
        'captcha': env('THROTTLE_CAPTCHA', default='30/min'),
        'enquiry': env('THROTTLE_ENQUIRY', default='5/min'),
        'track': env('THROTTLE_TRACK', default='120/min'),
        'comment': env('THROTTLE_COMMENT', default='5/min'),
        # The assistant is anonymous and every question costs an LLM call, so
        # this throttle is a spend control as much as an abuse control.
        'chat': env('THROTTLE_CHAT', default='20/min'),
    },
}


# Site assistant (RAG chatbot)
# ------------------------------------------------------------------
# API keys are read from the environment and used ONLY server-side. They are
# never serialised into any API response and never reach the browser — the
# React widget talks to /api/v1/chat/, and Django talks to the provider. A key
# shipped to the client is a key anyone can read out of the network tab and
# spend.
#
# Both providers are OpenAI-compatible, so one client handles either. They are
# tried in CHAT_PROVIDER_CHAIN order and the first that answers wins; if all of
# them fail the assistant falls back to extractive answers (see chatbot/llm.py)
# rather than erroring. Multi-provider because a marketing-site assistant that
# goes down with one vendor's API is not worth shipping.
CHAT_PROVIDERS = {
    'groq': {
        'API_KEY': env('GROQ_API_KEY', default=''),
        'BASE_URL': env('GROQ_BASE_URL', default='https://api.groq.com/openai/v1'),
        # Measured ~500ms on the grounded prompt and refused an out-of-corpus
        # question correctly. Alternatives on this account: openai/gpt-oss-120b,
        # openai/gpt-oss-20b, qwen/qwen3.6-27b, llama-3.1-8b-instant.
        'MODEL': env('GROQ_MODEL', default='llama-3.3-70b-versatile'),
    },
    'cerebras': {
        'API_KEY': env('CEREBRAS_API_KEY', default=''),
        'BASE_URL': env('CEREBRAS_BASE_URL', default='https://api.cerebras.ai/v1'),
        # Available on that account: gpt-oss-120b, zai-glm-4.7, gemma-4-31b.
        'MODEL': env('CEREBRAS_MODEL', default='gpt-oss-120b'),
    },
}

# Order matters. Groq leads because it is the account with usable credit;
# Cerebras is second and currently returns 402 (see chatbot/llm.py), so it
# costs one fast failed request before the chain moves on. Drop it from this
# list to skip it entirely.
CHAT_PROVIDER_CHAIN = env.list('CHAT_PROVIDER_CHAIN', default=['groq', 'cerebras'])

CHAT_LLM = {
    # Answers are two or three sentences by design; this is a ceiling, not a
    # target, and it caps the cost of a single question.
    'MAX_TOKENS': env.int('CHAT_MAX_TOKENS', default=600),
    # Both providers are sub-second normally. A long timeout would just hold a
    # visitor on a spinner when something is wrong — the extractive fallback is
    # better than waiting.
    'TIMEOUT_SECONDS': env.int('CHAT_TIMEOUT_SECONDS', default=15),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env.int('ACCESS_TOKEN_LIFETIME_MINUTES', default=15)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env.int('REFRESH_TOKEN_LIFETIME_DAYS', default=7)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# How the JWT pair is stored in the browser. Everything is HttpOnly, so page
# JavaScript can never read a token.
AUTH_COOKIE = {
    'ACCESS_NAME': env('AUTH_COOKIE_ACCESS_NAME', default='glaze_access'),
    'REFRESH_NAME': env('AUTH_COOKIE_REFRESH_NAME', default='glaze_refresh'),
    'PATH': '/',
    # The refresh cookie is only sent to the endpoints that actually need it.
    'REFRESH_PATH': '/api/v1/auth/',
    'DOMAIN': env('AUTH_COOKIE_DOMAIN', default=None),
    # HTTPS-only in production; a Secure cookie is dropped over plain http.
    # Unset in .env means "follow DEBUG".
    'SECURE': _env_bool('AUTH_COOKIE_SECURE', default=not DEBUG),
    # 'Lax' works while the SPA and API share a site. Cross-site (different
    # domains) requires 'None' + SECURE=True.
    'SAMESITE': env('AUTH_COOKIE_SAMESITE', default='Lax'),
    # On by default. Cookie-borne credentials are attached by the browser to
    # cross-origin form posts too, so without this the admin API is CSRF-open.
    # services/api.js primes the token from /auth/csrf/ and sends X-CSRFToken on
    # every unsafe request, so this costs the SPA nothing.
    'ENFORCE_CSRF': _env_bool('AUTH_COOKIE_ENFORCE_CSRF', default=True),
}


# Admin login hardening
# ------------------------------------------------------------------
# Layered, because each layer covers a different attack:
#   captcha  -> stops unattended scripted submission
#   lockout  -> stops slow distributed guessing that stays under the throttle
#   throttle -> stops volume (REST_FRAMEWORK above)
#   Argon2   -> makes a stolen hash expensive to crack offline

ADMIN_LOGIN = {
    # Failed attempts against one account before it stops accepting passwords.
    'MAX_ACCOUNT_FAILURES': env.int('ADMIN_MAX_ACCOUNT_FAILURES', default=5),
    # Failed attempts from one IP across ANY account. Catches spraying, where a
    # single password is tried against many accounts and no account trips.
    'MAX_IP_FAILURES': env.int('ADMIN_MAX_IP_FAILURES', default=20),
    # First lockout duration. Each consecutive lockout doubles it, capped below.
    'LOCKOUT_SECONDS': env.int('ADMIN_LOCKOUT_SECONDS', default=300),
    'LOCKOUT_MAX_SECONDS': env.int('ADMIN_LOCKOUT_MAX_SECONDS', default=86400),
    # Window over which failures accumulate; older ones no longer count.
    'FAILURE_WINDOW_SECONDS': env.int('ADMIN_FAILURE_WINDOW_SECONDS', default=900),
    # Trust X-Forwarded-For only when a proxy you control sets it. Left off, the
    # client IP is taken from REMOTE_ADDR, which cannot be spoofed by the client.
    # Turning this on without a proxy in front lets an attacker forge a fresh IP
    # per request and walk straight through the per-IP lockout.
    'TRUST_FORWARDED_FOR': env.bool('ADMIN_TRUST_FORWARDED_FOR', default=False),
}

# Captcha
# ------------------------------------------------------------------
# Default provider is 'internal': a stateless HMAC-signed challenge rendered as
# SVG by the server. It needs no third-party account, sends no visitor data off
# the box, and works offline. See account/captcha.py for the construction.
# Set CAPTCHA_PROVIDER to recaptcha | hcaptcha | turnstile to use a hosted one.
CAPTCHA = {
    'PROVIDER': env('CAPTCHA_PROVIDER', default='internal'),
    'SECRET_KEY': env('CAPTCHA_SECRET_KEY', default=''),
    'SITE_KEY': env('CAPTCHA_SITE_KEY', default=''),
    # How long a challenge stays solvable. Short enough that a harvested
    # challenge is worthless, long enough for a person to read and type it.
    'TTL_SECONDS': env.int('CAPTCHA_TTL_SECONDS', default=300),
    'LENGTH': env.int('CAPTCHA_LENGTH', default=5),
}


# Email — enquiry notifications and the customer auto-reply.
# Recipients, subject prefix and the auto-reply body are NOT here: they are
# editable in the admin panel and live in siteconfig.ContactSettings. Only the
# transport belongs in the environment.
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
# Gmail: an APP PASSWORD, never the account password — see .env.example.
# Whitespace stripped because Google displays it in four groups of four and it
# gets pasted that way; the spaces are not part of the secret, and an SMTP
# login that fails on an invisible trailing space is a bad afternoon.
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='').replace(' ', '')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)

# Seconds. Django's default is None — no timeout at all — which on a hung
# relay holds the worker open until the client gives up. Enquiry submission is
# a request a visitor is watching a spinner for.
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=15)

# ⚠ On Gmail this MUST be EMAIL_HOST_USER or one of its verified aliases.
# Gmail rewrites a From it does not own, so a no-reply@ address here would be
# silently replaced by the authenticated account on every message.
DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL',
    default='Glaze Window Systems <info@glazewindowsystems.com>',
)
# Django's own error mail (ADMINS) uses this prefix; keeping it distinct from
# the enquiry prefix means a 500 report cannot be mistaken for a customer.
EMAIL_SUBJECT_PREFIX = '[Glaze server] '


# The canonical public origin — scheme, host, no trailing slash.
#
# Every absolute URL in robots.txt, llms.txt, sitemap.xml and the JSON-LD is
# built from this. It has to be configured in production because Django sits
# behind a proxy there and `request.get_host()` is the INTERNAL host: a
# sitemap full of http://127.0.0.1:8000/… is a sitemap of URLs that do not
# exist. Left blank it falls back to the request's own origin, which is what
# makes local development work with no configuration.
#
# ⚠ Pick www or non-www once and 301 the other. Two hostnames serving the same
# pages is the same page indexed twice, competing with itself.
SITE_URL = env('SITE_URL', default='')

# Stamped on the sitemap's static routes, which have no updated_at of their
# own. A date, not a timestamp: a lastmod that changes on every deploy teaches
# crawlers that lastmod means nothing here.
SITE_LAST_DEPLOYED = env('SITE_LAST_DEPLOYED', default='')


# Transport security. All of these are no-ops on plain http, so they are tied to
# DEBUG rather than set unconditionally — otherwise local development over
# http://localhost would redirect itself into a loop.
if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The SPA reads this one to echo it back as X-CSRFToken, so it cannot be
    # HttpOnly. That is the documented Django pattern and is safe: the token is
    # useless to an attacker who cannot also read the response.
    CSRF_COOKIE_HTTPONLY = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# CORS — the SPA must send credentials, so an explicit origin allowlist is required
# ('*' is not permitted alongside credentials).

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:5173'])
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
