# Generated by Django 6.0.7 on 2026-07-31 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('accent_color', models.CharField(default='#726655', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'blog_category',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'db_table': 'blog_tag',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('role', models.CharField(blank=True, help_text='e.g. Head of Systems Engineering', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_author',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='1–2 sentences, used in listings and as the meta description fallback.', max_length=400)),
                ('content', models.TextField(help_text='HTML is accepted: h2, h3, p, ul, ol, table, blockquote. Callout components: wrap in <div class="bl-tip">, bl-expert, bl-insight, bl-note, bl-warning.')),
                ('takeaways', models.TextField(blank=True, help_text='One per line. Rendered as the Key Takeaways box. Blank hides the box.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=250)),
                ('show_author', models.BooleanField(default=True, help_text='Show the byline on the article.')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, max_length=80)),
                ('canonical_url', models.URLField(blank=True, help_text='Set only when this article also lives elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Ask search engines not to index this article.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Shown prominently on the blog listing.')),
                ('comments_enabled', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reading_time', models.PositiveIntegerField(default=1, help_text='Minutes. Recalculated on save.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'db_table': 'blog_post',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(help_text='Never published. Used only to reach the commenter.', max_length=254)),
                ('body', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('spam', 'Spam')], db_index=True, default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'db_table': 'blog_comment',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'),
        ),
    ]
