# Generated by Django 6.0.7 on 2026-07-31 11:30

import siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_emails', models.TextField(default='info@glazewindowsystems.com', help_text='Comma-separated. Every address receives every enquiry.', validators=[siteconfig.models.validate_email_list])),
                ('subject_prefix', models.CharField(default='[Glaze Enquiry]', help_text='Prepended to every notification subject — helps filter in your inbox.', max_length=60)),
                ('notify_enabled', models.BooleanField(default=True, help_text='Send the internal notification email on each enquiry.')),
                ('auto_reply_enabled', models.BooleanField(default=True, help_text='Send a confirmation email to the customer after they submit.')),
                ('auto_reply_subject', models.CharField(default='Thank you for contacting Glaze Window Systems', max_length=200)),
                ('auto_reply_html', models.TextField(default='<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Thank You — Glaze Window Systems</title>\n</head>\n<body style="margin:0;padding:0;background:#F5F5F3;font-family:\'Helvetica Neue\',Helvetica,Arial,sans-serif;">\n<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F3;padding:40px 0;">\n  <tr>\n    <td align="center">\n\n      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;overflow:hidden;box-shadow:0 2px 18px rgba(27,27,27,0.08);max-width:600px;width:100%;">\n\n        <tr>\n          <td style="background:#1B1B1B;padding:36px 40px;text-align:center;">\n            <div style="font-size:26px;font-weight:300;color:#ffffff;letter-spacing:6px;text-transform:uppercase;">\n              Glaze\n            </div>\n            <div style="font-family:\'Courier New\',monospace;font-size:10px;color:#A79A87;letter-spacing:3px;text-transform:uppercase;margin-top:10px;">\n              Designed to Disappear\n            </div>\n          </td>\n        </tr>\n\n        <tr>\n          <td style="background:#726655;height:2px;font-size:0;line-height:0;">&nbsp;</td>\n        </tr>\n\n        <tr>\n          <td style="padding:40px;">\n\n            <h1 style="margin:0 0 14px;font-size:24px;font-weight:400;color:#1B1B1B;font-family:Georgia,\'Times New Roman\',serif;">\n              Thank you, {{name}}.\n            </h1>\n\n            <p style="margin:0 0 26px;font-size:14px;color:#5A5A5A;line-height:1.8;">\n              We have received your enquiry about the <strong style="color:#726655;">{{system}}</strong> system.\n              One of our specialists will review it and come back to you within one working day.\n            </p>\n\n            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F3;border-left:2px solid #726655;margin-bottom:28px;">\n              <tr>\n                <td style="padding:22px 24px;">\n                  <div style="font-family:\'Courier New\',monospace;font-size:9px;letter-spacing:3px;text-transform:uppercase;color:#8A8A8A;margin-bottom:14px;">\n                    Need us sooner?\n                  </div>\n                  <table cellpadding="0" cellspacing="0" width="100%">\n                    <tr>\n                      <td style="padding:5px 0;font-size:13px;color:#1B1B1B;">\n                        <strong style="font-weight:600;">Call</strong>\n                        &nbsp;<a href="tel:{{contact_phone}}" style="color:#726655;text-decoration:none;">{{contact_phone}}</a>\n                      </td>\n                    </tr>\n                    <tr>\n                      <td style="padding:5px 0;font-size:13px;color:#1B1B1B;">\n                        <strong style="font-weight:600;">Email</strong>\n                        &nbsp;<a href="mailto:{{contact_email}}" style="color:#726655;text-decoration:none;">{{contact_email}}</a>\n                      </td>\n                    </tr>\n                    <tr>\n                      <td style="padding:5px 0;font-size:13px;color:#1B1B1B;">\n                        <strong style="font-weight:600;">WhatsApp</strong>\n                        &nbsp;<a href="{{whatsapp_link}}" style="color:#726655;text-decoration:none;">Message our team</a>\n                      </td>\n                    </tr>\n                  </table>\n                </td>\n              </tr>\n            </table>\n\n            <table width="100%" cellpadding="0" cellspacing="0" style="background:#1B1B1B;margin-bottom:28px;">\n              <tr>\n                <td style="padding:26px;text-align:center;">\n                  <div style="font-size:22px;font-weight:300;color:#ffffff;letter-spacing:1px;">Aluminium since 1989</div>\n                  <div style="font-size:12px;color:#A79A87;margin-top:8px;">\n                    Sliding &nbsp;·&nbsp; Casement &nbsp;·&nbsp; Lift &amp; Slide &nbsp;·&nbsp; Bi-Fold &nbsp;·&nbsp; Pivot &nbsp;·&nbsp; Fixed\n                  </div>\n                </td>\n              </tr>\n            </table>\n\n            <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:8px;">\n              <tr>\n                <td style="padding-bottom:12px;font-family:\'Courier New\',monospace;font-size:9px;letter-spacing:3px;text-transform:uppercase;color:#8A8A8A;">\n                  Why architects specify Glaze\n                </td>\n              </tr>\n              <tr>\n                <td style="font-size:13px;color:#3A3A3A;line-height:2;">\n                  — Thermally broken aluminium profiles<br>\n                  — Tested to 1200 Pa water tightness<br>\n                  — Sightlines from 22 mm<br>\n                  — German hardware, 25,000-cycle rated<br>\n                  — In-house fabrication and installation\n                </td>\n              </tr>\n            </table>\n\n          </td>\n        </tr>\n\n        <tr>\n          <td style="background:#1B1B1B;padding:28px 40px;text-align:center;">\n            <div style="font-size:15px;font-weight:300;color:#ffffff;letter-spacing:4px;text-transform:uppercase;margin-bottom:10px;">\n              {{site_name}}\n            </div>\n            <div style="font-size:12px;color:rgba(255,255,255,0.55);line-height:1.8;">\n              A Sagar Asia Company &nbsp;·&nbsp; Jubilee Hills, Hyderabad\n            </div>\n            <div style="margin-top:16px;font-size:12px;">\n              <a href="tel:{{contact_phone}}" style="color:#A79A87;text-decoration:none;">{{contact_phone}}</a>\n              &nbsp;&nbsp;|&nbsp;&nbsp;\n              <a href="mailto:{{contact_email}}" style="color:#A79A87;text-decoration:none;">{{contact_email}}</a>\n            </div>\n            <div style="margin-top:18px;font-size:10px;color:rgba(255,255,255,0.28);">\n              You received this email because you submitted an enquiry on our website. &copy; {{year}}\n            </div>\n          </td>\n        </tr>\n\n      </table>\n\n    </td>\n  </tr>\n</table>\n</body>\n</html>\n')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact settings',
                'verbose_name_plural': 'contact settings',
                'db_table': 'siteconfig_contact_settings',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('enquiry_type', models.CharField(blank=True, max_length=60)),
                ('system', models.CharField(blank=True, max_length=60)),
                ('variant', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('auto_replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'db_table': 'siteconfig_enquiry',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Glaze Window Systems', max_length=120)),
                ('tagline', models.CharField(default='Designed to Disappear.', max_length=200)),
                ('contact_email', models.EmailField(default='info@glazewindowsystems.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 76750 23939', max_length=40)),
                ('contact_phone_secondary', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(default='Glaze Windows System, 4th Floor, Road No. 5,\nJubilee Hills, Hyderabad, Telangana 500033')),
                ('map_url', models.URLField(blank=True, default='https://www.google.com/maps/search/?api=1&query=Glaze%20Windows%20System%2C%20Jubilee%20Hills%2C%20Hyderabad', max_length=600)),
                ('business_hours', models.CharField(default='Mon – Sat · 10:00 – 19:00', max_length=200)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_number', models.CharField(blank=True, default='+917675023939', help_text='Include the country code, e.g. +917675023939', max_length=40)),
                ('whatsapp_label', models.CharField(default='Enquire on WhatsApp', max_length=80)),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/glaze_window_systems/')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/Glazewindowsystems')),
                ('linkedin_url', models.URLField(blank=True, default='https://in.linkedin.com/company/glaze-window-systems')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@GlazeWindowSystems')),
                ('system_page_layout', models.CharField(choices=[('editorial', 'Editorial (full scroll experience)'), ('compact', 'Clean compact view (fast navigation)')], default='editorial', help_text='Default layout for the six system pages unless a system overrides it.', max_length=20)),
                ('meta_title_suffix', models.CharField(default=' — Glaze', max_length=80)),
                ('default_meta_description', models.CharField(default='Premium aluminium window and door systems, engineered to disappear into the architecture.', max_length=200)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('ga_measurement_id', models.CharField(blank=True, help_text='Google Analytics 4 measurement ID (G-XXXXXXX). Leave blank to use only the built-in analytics.', max_length=40)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(default='We are making some improvements. Please check back shortly.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'db_table': 'siteconfig_site_settings',
            },
        ),
    ]
