# Generated by Django 6.0.7 on 2026-08-04 08:52

import siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='contact_recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Enquiries from the Contact page form. Blank uses the default list.', validators=[siteconfig.models.validate_optional_email_list]),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='general_recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Everything else — the assistant, direct API submissions, and any page that is not the contact form or a system page. Blank uses the default list.', validators=[siteconfig.models.validate_optional_email_list]),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='product_recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Enquiries raised from a system page, carrying the configured system, variant, series, glass and finish. Blank uses the default list.', validators=[siteconfig.models.validate_optional_email_list]),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='subject_include_category',
            field=models.BooleanField(default=True, help_text='Add the enquiry type to the subject, e.g. "[Glaze Enquiry] [Product] Priya Sharma". Worth leaving on if several types share one inbox — it is what a mail rule can filter on.'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('contact', 'Contact form'), ('product', 'Product / system page')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='auto_reply_html',
            field=models.TextField(default='<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Thank You — Glaze Window Systems</title>\n</head>\n<body style="margin:0;padding:0;background:#F5F5F3;font-family:\'Helvetica Neue\',Helvetica,Arial,sans-serif;">\n<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F3;padding:40px 0;">\n  <tr>\n    <td align="center">\n\n      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;overflow:hidden;box-shadow:0 2px 18px rgba(27,27,27,0.08);max-width:600px;width:100%;">\n\n        <tr>\n          <td style="background:#1B1B1B;padding:36px 40px;text-align:center;">\n            <div style="font-size:26px;font-weight:300;color:#ffffff;letter-spacing:6px;text-transform:uppercase;">\n              Glaze\n            </div>\n            <div style="font-family:\'Courier New\',monospace;font-size:10px;color:#A79A87;letter-spacing:3px;text-transform:uppercase;margin-top:10px;">\n              Designed to Disappear\n            </div>\n          </td>\n        </tr>\n\n        <tr>\n          <td style="background:#726655;height:2px;font-size:0;line-height:0;">&nbsp;</td>\n        </tr>\n\n        <tr>\n          <td style="padding:40px;">\n\n            <h1 style="margin:0 0 14px;font-size:24px;font-weight:400;color:#1B1B1B;font-family:Georgia,\'Times New Roman\',serif;">\n              Thank you, {{name}}.\n            </h1>\n\n            <p style="margin:0 0 26px;font-size:14px;color:#5A5A5A;line-height:1.8;">\n              We have received your enquiry about the <strong style="color:#726655;">{{system}}</strong> system.\n              One of our specialists will review it and come back to you within one working day.\n            </p>\n\n            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F3;border-left:2px solid #726655;margin-bottom:28px;">\n              <tr>\n                <td style="padding:22px 24px;">\n                  <div style="font-family:\'Courier New\',monospace;font-size:9px;letter-spacing:3px;text-transform:uppercase;color:#8A8A8A;margin-bottom:14px;">\n                    Need us sooner?\n                  </div>\n                  <table cellpadding="0" cellspacing="0" width="100%">\n                    <tr>\n                      <td style="padding:5px 0;font-size:13px;color:#1B1B1B;">\n                        <strong style="font-weight:600;">Call</strong>\n                        &nbsp;<a href="tel:{{contact_phone}}" style="color:#726655;text-decoration:none;">{{contact_phone}}</a>\n                      </td>\n                    </tr>\n                    <tr>\n                      <td style="padding:5px 0;font-size:13px;color:#1B1B1B;">\n                        <strong style="font-weight:600;">Email</strong>\n                        &nbsp;<a href="mailto:{{contact_email}}" style="color:#726655;text-decoration:none;">{{contact_email}}</a>\n                      </td>\n                    </tr>\n                    <tr>\n                      <td style="padding:5px 0;font-size:13px;color:#1B1B1B;">\n                        <strong style="font-weight:600;">WhatsApp</strong>\n                        &nbsp;<a href="{{whatsapp_link}}" style="color:#726655;text-decoration:none;">Message our team</a>\n                      </td>\n                    </tr>\n                  </table>\n                </td>\n              </tr>\n            </table>\n\n            <table width="100%" cellpadding="0" cellspacing="0" style="background:#1B1B1B;margin-bottom:28px;">\n              <tr>\n                <td style="padding:26px;text-align:center;">\n                  <div style="font-size:22px;font-weight:300;color:#ffffff;letter-spacing:1px;">Aluminium since 1989</div>\n                  <div style="font-size:12px;color:#A79A87;margin-top:8px;">\n                    Sliding &nbsp;·&nbsp; Casement &nbsp;·&nbsp; Lift &amp; Slide &nbsp;·&nbsp; Bi-Fold &nbsp;·&nbsp; Pivot &nbsp;·&nbsp; Fixed\n                  </div>\n                </td>\n              </tr>\n            </table>\n\n            <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:8px;">\n              <tr>\n                <td style="padding-bottom:12px;font-family:\'Courier New\',monospace;font-size:9px;letter-spacing:3px;text-transform:uppercase;color:#8A8A8A;">\n                  Why architects specify Glaze\n                </td>\n              </tr>\n              <tr>\n                <td style="font-size:13px;color:#3A3A3A;line-height:2;">\n                  — Thermally broken aluminium profiles<br>\n                  — Tested to 1200 Pa water tightness<br>\n                  — Sightlines from 22 mm<br>\n                  — German hardware, 25,000-cycle rated<br>\n                  — In-house fabrication and installation\n                </td>\n              </tr>\n            </table>\n\n          </td>\n        </tr>\n\n        <tr>\n          <td style="background:#1B1B1B;padding:28px 40px;text-align:center;">\n            <div style="font-size:15px;font-weight:300;color:#ffffff;letter-spacing:4px;text-transform:uppercase;margin-bottom:10px;">\n              {{site_name}}\n            </div>\n            <div style="font-size:12px;color:rgba(255,255,255,0.55);line-height:1.8;">\n              Jubilee Hills, Hyderabad\n            </div>\n            <div style="margin-top:16px;font-size:12px;">\n              <a href="tel:{{contact_phone}}" style="color:#A79A87;text-decoration:none;">{{contact_phone}}</a>\n              &nbsp;&nbsp;|&nbsp;&nbsp;\n              <a href="mailto:{{contact_email}}" style="color:#A79A87;text-decoration:none;">{{contact_email}}</a>\n            </div>\n            <div style="margin-top:18px;font-size:10px;color:rgba(255,255,255,0.28);">\n              You received this email because you submitted an enquiry on our website. &copy; {{year}}\n            </div>\n          </td>\n        </tr>\n\n      </table>\n\n    </td>\n  </tr>\n</table>\n</body>\n</html>\n'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='recipient_emails',
            field=models.TextField(default='info@glazewindowsystems.com', help_text='Comma-separated. The default list — used for any enquiry type that has no list of its own, and the reason one is required.', validators=[siteconfig.models.validate_email_list]),
        ),
    ]
