# Generated by Django 6.0.7 on 2026-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_backfill_enquiry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bing_site_verification',
            field=models.CharField(blank=True, help_text='The content value of the msvalidate.01 meta tag, for Bing Webmaster Tools — which also feeds ChatGPT search.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_domain_verification',
            field=models.CharField(blank=True, help_text='The content value of facebook-domain-verification, from Meta Business Settings. Required before the pixel can be used for catalogue ads.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='The content value of the google-site-verification meta tag, for Search Console. Just the token, not the whole tag.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gtm_container_id',
            field=models.CharField(blank=True, help_text='Google Tag Manager container (GTM-XXXXXXX). Use this INSTEAD of the individual ids above and below once the tracking stack is non-trivial — running GTM and a hard-coded tag together double-counts everything.', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=17.4239, help_text='Decimal degrees, e.g. 17.423900. Right-click the premises in Google Maps.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=78.4138, help_text='Decimal degrees, e.g. 78.413800.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Meta (Facebook/Instagram) Pixel ID — the 15-16 digit number from Events Manager. Powers ad conversion tracking and retargeting audiences.', max_length=32),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_track_enquiries',
            field=models.BooleanField(default=True, help_text='Fire a Lead event when someone submits an enquiry. This is what makes the pixel worth having — without a conversion event the ad platform is optimising blind.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ga_measurement_id',
            field=models.CharField(blank=True, help_text='Google Analytics 4 measurement ID (G-XXXXXXXX). Leave blank to use only the built-in, cookie-free analytics.', max_length=40),
        ),
    ]
