# Generated by Django 6.0.7 on 2026-08-07 20:12

import django.db.models.deletion
import siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_sitesettings_bing_site_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='budget',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='openings',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='systems',
            field=models.CharField(blank=True, help_text='Every system chosen, comma-separated. `system` holds the first.', max_length=300),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='timeline',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='EnquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=siteconfig.models.enquiry_attachment_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='siteconfig.enquiry')),
            ],
            options={
                'db_table': 'siteconfig_enquiry_attachment',
                'ordering': ('id',),
            },
        ),
    ]
