# Generated by Django 6.0.7 on 2026-08-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_enquiry_budget_enquiry_city_enquiry_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
